apiVersion: v2
name: mcp-server-go
description: A Helm chart for MCP (Model Context Protocol) Demo Server - Go Implementation
type: application
version: 1.0.2
appVersion: "1.0.2"
keywords:
  - mcp
  - model-context-protocol
  - go
  - server
home: https://github.com/freemangh/mcp-demo-server
sources:
  - https://github.com/freemangh/mcp-demo-server
maintainers:
  - name: Yevhen Khvastunov
    email: khvastunov@gmail.com
